### ISSUE TITLE
3장 오픈 사이언스 대, 중제목 제목 통일 필요

### ISSUE THREAD

**Issue by SunkyeongLee** [ohdsi-korea/TheBookOfOhdsiKorea#101]
Open Science장의 제목을 영어 그대로 오픈 사이언스, 오픈 스탠다드, 오픈 소스 등등으로 통일할 것인지, 열린 과학 혹은 개방형 과학, 열린 기준, 열린 원천 등등으로 직역해서 사용할 것인지에 대한 통일도 필요해보입니다.

**Comment by chandryou** [comment]
한글로 '오픈 사이언스', '오픈 스탠다드', '오픈 소스' 하는 게 어떨까 합니다. 
개방형 과학 할 수도 있는데.. 아무도 못 알아 들을 거 같아요..

**Comment by SunkyeongLee** [comment]
그럼 나머지 소제목들도 오픈 스탠다드 오픈 소스로 통일하겠습니다

**Comment by SunkyeongLee** [comment]
0127badb0982e8338633ad997fadc9fcba9aa5aa
