### ISSUE TITLE
5장 추가 수정 사항

### ISSUE THREAD

**Issue by chandryou** [ohdsi-korea/TheBookOfOhdsiKorea#103]
5.2.10 수명주기

후속 코드 없이 더 이상 사용되지 않는 개념
VALID_END_DATE: 사용 중단을 나타내는 과거의 날 또는 해당 용어가 알려지지 않은 경우 concept이 누락되거나 비활성화 된 vocabulary의 갱신일이 알려지지 않은 경우.
=>
  VALID_END_DATE: 사용 중단을 나타내는 과거의 날짜,  또는 해당 날짜를 알수 없는 경우, concept이 누락되거나 비활성화 된 vocabulary 갱신일 

후속 코드가 있는 업그레이드 된 개념
VALID_END_DATE: 과거에 업그레이드를 나타내는 날 또는 업그레이드가 포함 된 vocabulary의 갱신일을 알 수 없는 경우.
=>
  VALID_END_DATE:  업그레이드를 나타내는 과거의 날짜, 또는 해당 날짜를 알수 없는 경우,  업그레이드가 추가된  vocabulary 갱신일 

다른 새로운 concept에 대한 재사용 코드
VALID_END_DATE: 사용 중단을 나타내는 과거의 날 또는 해당 용어가 알려지지 않은 경우 concept이 누락되거나 비활성화 된 vocabulary의 갱신일이 알려지지 않은 경우.
=> 
 VALID_END_DATE: 사용 중단을 나타내는 과거의 날짜,  또는 해당 날짜를 알수 없는 경우,  concept 이 누락되거나 inactive 로 설정된  vocabulary 갱신일   

  5.2.10 수명주기  

비활성 관계는 내부처리만을 위한 Palls 시스템에서 유지된다 

=>   ( (오타수정 포함하여 의역)  Palls => Pallas   )

비활성화된 relationship은 Pallas 시스템 내에서 내부처리 용도로만 사용되도록 보관된다. 

5.3.1 매핑 관계  
Up-hill 매핑은 정보가 유실 되도 표준 연구 use case 들과 관련 없다고 간주될 때에만 사용해야 한다.
=>
Up-hill 매핑은 정보가 유실되도 표준 연구 사례들을 진행하는데 문제 없다고 간주될 때만 사용해야 한다.  
5.3.4 동일 용어의 개념들 간 관계

이들 중 다수는 clinical events 사이의 관계를 정의하고 정보 검색에 이용될 수 있다. 예를 들어, disorders of the urethra는“finding site of” 관계에 따라 찾을 수 있다. (표5.5참조)

=>

  이들 중 다수는 clinical events 간의 관계를 정의하여 정보 검색에 이용될 수 있다. 예를 들어, disorders of the urethra는“finding site of” 관계를 따라가면 찾을 수 있다. (표5.5참조) 

 

일반적으로, SNOMED와 같이 표준 개념을 도출하는데, 사용되는 vocabularies는 더 나은 구조화를 위해 선택되며, 따라서 더 높은 품질의 내부 관계를 갖는 경향이 있다.

=>

일반적으로, SNOMED와 같은 표준 개념을 도출하는데 사용되는 vocabularies는 자료 분류와 구조화를 더 잘 해주기 때문에, 내부 관계의 품질을 높여주는 데 도움이 된다.    

5.6.2 인종과 민족

이것들은 미국 정부가 이것을 어떻게 정의하는지에 대한 정의를 따른다. 

=>

인종과 민족은 미국 정부가 지정한  정의를 따른다. 

민족은 Hispanic 또는 non-Hispanic 인구를 구분하는데, 인종은 상관 없다. 

=>

민족은 인종과 상관없이, Hispanic 또는 non-Hispanic 인구를 구분한다. 

6.4 처치 코드 시스템

이러한 서비스의 많은 부분이 procedure 도메인 하에 포함되어 있지만, 많은 개념들이 이 도메인 밖에 벗어나 있다.

=>

이러한 서비스의 많은 부분이 procedure 도메인 아래에 포함되어 있지만, 많은 개념들이 이 도메인 밖에 벗어나 있다.

5.6.7 제공자 및 전문의

전문의는 제공자인 “의사” (Physician)의 하위개념이다 (마침표 빠져있음)

=> 전문의는 제공자인 “의사” (Physician)의 하위개념이다.

 

7 요약

모든 개념들은 한 개의 도메인에 선정되는데, 개념에 의해 표현되는 사건이 CDM 의 저장되는 위치를 관리한다.  

=>

모든 개념들은 한 개의 도메인에 선정되는데, 도메인은 개념에 의해 표현되는 사건이 CDM 의 저장되는 위치를 관리한다.   
 

다른 vocabularies에서 동등한 의미를 갖는 개념들은 그 중 하나에 매칭되는데, 이는 표준 개념을 가리킨다. 다른 개념들은 소스 개념들이다. 

=>
다른 vocabularies에서 동등한 의미를 갖는 개념들은 그 중 하나에 매칭되는데, 그 것이 표준개념으로  지정된 개념이다.  다른 개념들은 소스 개념들이다.

**Comment by SunkyeongLee** [comment]
d599e51683791cf8e2000335a92e34b024dc6b3f
