### ISSUE TITLE
e.g에 대한 통일

### ISSUE THREAD

**Issue by SunkyeongLee** [ohdsi-korea/TheBookOfOhdsiKorea#115]
"예를 들어"로 통일할 것인지, "예: "로 통일할 것인지 논의가 필요할 것 같습니다

**Comment by chandryou** [comment]
'예를 들어,' 가 좋지 않을까 싶어요 ㅎ

**Comment by SunkyeongLee** [comment]
6dd51826bd3e0daae1fa499c6647c88aacb21569
