### ISSUE TITLE
중제목 형식 통일

### ISSUE THREAD

**Issue by SunkyeongLee** [ohdsi-korea/TheBookOfOhdsiKorea#118]
어떤 제목은 한글로만 되어있고 어떤 제목은 한글 제목 옆에 영어가 같이 있습니다

1.1 데이터에서 근거로의 여정 (The Journey from Data to Evidence)

4.1.2 표준화된 용어 구축 

모든 제목을 위의 형태로 통일하는게 좋을까요 아니면 아래의 형태로 통일하는게 좋을까요?

**Comment by chandryou** [comment]
가급적 한글 용어로만 통일하는 것이 좋겠습니다.

**Comment by SunkyeongLee** [comment]
0de9c6e621c92da8ba85bc2a427e1b601308a9b9
