### ISSUE TITLE
Table 4.6: VISIT_OCCURRENCE 테이블.

### ISSUE THREAD

**Issue by SooyoungYoo** [ohdsi-korea/TheBookOfOhdsiKorea#130]
원본 문서에서도 함께 수정이 필요한 오타인 것 같습니다.

ADMITTED_FROM_ SOURCE_CONCEPT_ID  --> ADMITTED_FROM_SOURCE_VALUE

**Comment by chandryou** [comment]
https://github.com/ohdsi-korea/TheBookOfOhdsiKorea/commit/62c1ea5406838e87ef8658f74abab85c6aad31d9
