### ISSUE TITLE
누락 부분 확인

### ISSUE THREAD

**Issue by chandryou** [ohdsi-korea/TheBookOfOhdsiKorea#139]
원문과 비교해서 누락된 부분 있는지 여부 확인 필요

Chapter 12 (PLP) 의 경우 맨 처음의 인용 부분이 누락된 것으로 확인됨.

**Comment by chandryou** [comment]
'Chapter 12 (PLP) 의 경우 맨 처음의 인용 부분이 누락된 것으로 확인됨.'
은 Clinical validity chapter와 헷가렬서 제가 잘못 확인한 부분입니다. 누락되지 않았었습니다.

**Comment by SunkyeongLee** [comment]
4bfe09b68390f1428dc782e1b05781e8b5205488
fa1873b611cfff590e38f8d6334db68831432e04
29b5df74c4ccc03bcafaaa36f5d0f46e139896c6
