### ISSUE TITLE
13장 환자수준예측

### ISSUE THREAD

**Issue by ChungsooKim** [ohdsi-korea/TheBookOfOhdsiKorea#241]
안녕하세요 
아주대학교 의료정보학과 통합과정 김청수입니다.

13장에서 몇가지 minor 한 부분을 발견하여 올려드립니다

1. 13.3.3 랜덤포레스트 1문단 마지막 문장 : 우리 패키지는 **Python에서 Random Forest의 sklearn 수행을 사용한다.** 
-> Python의  **Sklearn 내 Random forest 를 사용한다.**

2. 13.6.3 실행설정 1문단 2번째 점 : “최소 공변량 발생: 만약 어떤 공변량이 지정한 값보다 **작적** 수의 대상에서만 발생하면 제거된다:
-> “최소 공변량 발생: 만약 어떤 공변량이 지정한 값보다 **적은** 수의 대상에서 발생하면 제거된다:

3. 13.6.4 학습설정 1문단 1번째 점 : “검증/학습 세트를 분할하는 방법 지정 Specify how to split the test/train **se**:” 
-> “검증/학습 세트를 분할하는 방법 지정 Specify how to split the test/train **set**” 

4. 전반적인 runPlp 표기가 runPLP, runPLp, runplp 로 다양합니다...

감사합니다.
김청수 드림

**Comment by SunkyeongLee** [comment]
감사합니다! :)

aead37de8819fe69288d4c704f99a45f00cbced5
