### ISSUE TITLE
Ch4. The Common Data Model

### ISSUE THREAD

**Issue by chandryou** [ohdsi-korea/TheBookOfOhdsiKorea#31]
Ch4. The Common Data Model 번역
전호균 번역 예정

**Comment by neal1202** [comment]
1차 번역 50% 완료

- 테이블 명세 번역필요
- 테이블 관련 용어 통일 필요
- 마크 다운내에 링크 및 캡션 정리 필요

**Comment by neal1202** [comment]
1차 초벌 번역 완료
* concept, visit, observation, procedure등 용어 통일 필요
* 검수 필요

**Comment by chandryou** [comment]
@neal1202 초벌 번역 완료했으면 PR 남겨주세요.
