### ISSUE TITLE
Ch5. Standardized Vocabularies

### ISSUE THREAD

**Issue by chandryou** [ohdsi-korea/TheBookOfOhdsiKorea#32]
Ch5. Standardized Vocabularies 번역
장진성 선생님 번역 예정

**Comment by oovdd** [comment]
1차 초안 완료.

재검토를 통한 용어 통일, 문장 다듬기

Markdown이 아닌 워드에서 번역작업 진행 중 ( 금요일 이전으로 upload 예정)
