### ISSUE TITLE
Ch6. Extarct Transform Load

### ISSUE THREAD

**Issue by chandryou** [ohdsi-korea/TheBookOfOhdsiKorea#33]
Ch 6. Extarct Transform Load 번역
박지명 선생님 예정

**Comment by Jimyung6642** [comment]
현재까지 6.5 Step 4: Quality Control 까지 번역 완료(약 전체의 80%).

현재 이슈로는 용어 통일의 필요성
ex) Source Code, Vocabulary, Standard Vocabulary, Rabbit-In-A-Hat 등 일부 한국어로 번역하기 애매한 단어들이 존재.
