### ISSUE TITLE
Ch8. OHDSI Analytics Tools

### ISSUE THREAD

**Issue by chandryou** [ohdsi-korea/TheBookOfOhdsiKorea#35]
Ch8. OHDSI Analytics Tools 번역
신서정 선생님 번역 예정

**Comment by lucid0921** [comment]
- 진도 사항:   1차 Rmd 파일 생성 완료


- 챕터 이슈:

1.   (자동생성) Chapter 번호 상이 (배포본=Ch.8, 개인파일=Ch.5)
2.   (자동생성) Reference 번호 상이
3.   Reference 단락 및 12개의 링크가 생성됨


- 논의 사항:

1.   이슈 #1, #2는 다른 Chapter의 rmd 파일이 주어지면 자동으로 번호 일치될 것으로 예상
2.   배포본과 형식 맞춰지도록 코드 수정 필요
