### ISSUE TITLE
Ch11. Characterization

### ISSUE THREAD

**Issue by chandryou** [ohdsi-korea/TheBookOfOhdsiKorea#38]
Ch11. Characterization 번역
박유진 선생님 번역 예정

**Comment by ParkYouJin** [comment]
1차 초안 완료, 
아직 많이 다듬어야 함 
* 단어의 통일화 
* 문장 다듬기
* Figure및 table명에 대한 번역 필요

**Comment by ParkYouJin** [comment]
강미라교수님의 번역본과의 통합 및 Rmd로 변환 완료 후 PR send
