### ISSUE TITLE
Ch17. Software Validity

### ISSUE THREAD

**Issue by chandryou** [ohdsi-korea/TheBookOfOhdsiKorea#45]
Ch17. Software Validity 번역
김청수 선생님 번역 예정

**Comment by ChungsooKim** [comment]
10/8 오전까지 약 40% 진행
10/8 자정까지 1차 초안 완성 예정

**Comment by ChungsooKim** [comment]
1차 초안 완성 commit

**Comment by chandryou** [comment]
@ted9219 
1차 완성됐으면 PR 해주세요.
