### ISSUE TITLE
Ch18. Method Validity

### ISSUE THREAD

**Issue by chandryou** [ohdsi-korea/TheBookOfOhdsiKorea#46]
Ch18. Method Validity 번역
조재형 선생님 번역 예정

**Comment by JaehyeongCho** [comment]
번역된 용어 list
censored: 중도절단
covariate: 공변량
positive controls: 양성 대조군
negative controls: 음성 대조군
exposure: 노출
effect size: 효과 크기
bias: 편향
confounder: 교란 요인
sensitivity: 민감도
specificity: 특이도
error: 오차
null distribution: 귀무 분포
empirical: 경험적
sample: 표본
sampling: 표집

nominal: 공칭(公稱, 논의가 필요함)
random error: 임의 오차 (적합한지 논의가 필요함)
null: 귀무 (적합한지 논의가 필요함, 참고: 귀무, 영, null)
outcome: 결과 (적합한지 논의가 필요함)
simulated: 모의 (적합한지 논의가 필요함)

**Comment by JaehyeongCho** [comment]
**18.1 Design-Specific Diagnostics
18.2 Diagnostics for All Estimation
&nbsp;&nbsp;&nbsp;&nbsp;18.2.1 Negative Controls
&nbsp;&nbsp;&nbsp;&nbsp;18.2.2 Positive Controls
&nbsp;&nbsp;&nbsp;&nbsp;18.2.3 Empirical Evaluation
&nbsp;&nbsp;&nbsp;&nbsp;18.2.4 P-Value Calibration**
------------------------------------------ (19.10.18 14:00 기준 1차 번역)
&nbsp;&nbsp;&nbsp;&nbsp;18.2.5 Confidence Interval Calibration
&nbsp;&nbsp;&nbsp;&nbsp;18.2.6 Replication Across Sites
&nbsp;&nbsp;&nbsp;&nbsp;18.2.7 Sensitivity Analyses
18.3 Method Validation in Practice
&nbsp;&nbsp;&nbsp;&nbsp;18.3.1 Selecting Negative Controls
&nbsp;&nbsp;&nbsp;&nbsp;18.3.2 Including Controls
&nbsp;&nbsp;&nbsp;&nbsp;18.3.3 Empirical Performance
&nbsp;&nbsp;&nbsp;&nbsp;18.3.4 P-Value Calibration
&nbsp;&nbsp;&nbsp;&nbsp;18.3.5 Confidence Interval Calibration
&nbsp;&nbsp;&nbsp;&nbsp;18.3.6 Between-Database Heterogeneity
&nbsp;&nbsp;&nbsp;&nbsp;18.3.7 Sensitivity Analyses
18.4 OHDSI Methods BenchMark
18.5 Summary
