### ISSUE TITLE
각 장(chapter) 제목 한글로 번역

### ISSUE THREAD

**Issue by chandryou** [ohdsi-korea/TheBookOfOhdsiKorea#86]
각 장(chapter) 의 제목을 가급적 한글로 바꿔야 될 것 같습니다.

**Comment by SunkyeongLee** [comment]
2.2 검수 필요

**Comment by SunkyeongLee** [comment]
중제목 한글로 통일
9b416ed5c44f94a1335bd95a1d45d1760ddcd9f6

**Comment by SunkyeongLee** [comment]
1. OHDSI 커뮤니티
2. 어디서부터 시작할 것인가
3. 오픈 사이언스
4. 표준화된 용어
5. 추출 변환 적재
6. OHDSI 분석 툴
7. SQL과 R
8. 코호트 만들기
9. 환자 특성 분석
10. 인구 수준 예측
11. 환자 수준 예측
12. 근거의 질
13. 데이터의 질
14.  임상적 타당성
15. 소프트웨어의 타당성
16. 방법의 타당성
17. OHDSI 네트워크 리서치

정도면 괜찮을까요?

**Comment by chandryou** [comment]
다음이 더 좋을 것 같습니다.

OHDSI 커뮤니티
**OHDSI 시작하기**
오픈 사이언스
**OMOP 표준 용어**
**추출 변환 적재(ETL)**
OHDSI 분석 툴
SQL과 R
코호트 만들기
**임상적 특성 분석**
**인구 수준 추정**
환자 수준 예측
근거의 질
데이터의 질
임상적 타당성
소프트웨어의 타당성
**방법론적 타당성**
OHDSI 네트워크 리서치

정도가 어떨까 합니다. ^^

**Comment by SunkyeongLee** [comment]
37f5b03535d56ea1db44914a0404a853bbaf035e
