### ISSUE TITLE
순서 나열 형식에 대한 논의

### ISSUE THREAD

**Issue by SunkyeongLee** [ohdsi-korea/TheBookOfOhdsiKorea#94]
첫번째 형식은 다음과 같고
<img width="706" alt="Screen Shot 2019-10-18 at 9 52 49 PM" src="https://user-images.githubusercontent.com/25357982/67095802-c5d51800-f1f1-11e9-975d-1ae5cb3a7d4c.png">

두번째 형식은 다음과 같습니다.
<img width="706" alt="Screen Shot 2019-10-18 at 9 52 26 PM" src="https://user-images.githubusercontent.com/25357982/67095812-cd94bc80-f1f1-11e9-8ffe-b6c24596530e.png">

하위 형식이 조금 더 정렬되어 있는 느낌을 주는데 원문은 다음과 같은 형식으로 통일되어 있습니다. 어떤 방식으로 통일하는게 좋을까요? 
<img width="706" alt="Screen Shot 2019-10-18 at 9 55 17 PM" src="https://user-images.githubusercontent.com/25357982/67095921-092f8680-f1f2-11e9-9d62-d3a1ab0e3821.png">

**Comment by SunkyeongLee** [comment]
*정정합니다 상위 형식이 더 정렬되어 있는 느낌이에요

**Comment by chandryou** [comment]
가급적 원문을 따르는 게 어떨까요?

**Comment by SunkyeongLee** [comment]
그럼 원문을 따르는걸로 하겠습니다
