### ISSUE TITLE
명령문 마무리 형식에 대한 통일

### ISSUE THREAD

**Issue by SunkyeongLee** [ohdsi-korea/TheBookOfOhdsiKorea#95]
-하십시오 혹은 -해라 중 한가지로만 통일해야 할 것 같습니다.

어느것이 더 적합할까요?

**Comment by chandryou** [comment]
하십시오가 낫겠습니다만, '하자' 또는 가급적 '하십시오'를 쓰지 않도록 바꾸면 좋겠습니다.

**Comment by SunkyeongLee** [comment]
그럼 소제목에 대한 명령문은 어떻게 하는게 좋을까요?

Fix the error에 대해서 에러를 수정하라 보다는 에러 수정하기 정도의 명사로 바꿔주면 괜찮을까요?

**Comment by SunkyeongLee** [comment]
ed4751efdac3320920b7760668990d4f8c8abe94
9b416ed5c44f94a1335bd95a1d45d1760ddcd9f6
