### ISSUE TITLE
사진의 보충설명 영어 혹은 한국어로 통일

### ISSUE THREAD

**Issue by SunkyeongLee** [ohdsi-korea/TheBookOfOhdsiKorea#96]
사진의 보충설명을 영어 혹은 한국어 둘 중 하나로 통일해야 하겠습니다.

영어 혹은 한국어 중 어느걸로 통일할까요?

**Comment by chandryou** [comment]
한국어로 통일해야되겠습니다.

**Comment by SunkyeongLee** [comment]
c3a437438e933cb43edccc7696d52a08544ab126
