### ISSUE TITLE
언급되는 단어들에 대한 "" 형식 논의

### ISSUE THREAD

**Issue by SunkyeongLee** [ohdsi-korea/TheBookOfOhdsiKorea#98]
원문은 다음과 같고
<img width="697" alt="Screen Shot 2019-10-18 at 10 13 12 PM" src="https://user-images.githubusercontent.com/25357982/67097198-94aa1700-f1f4-11e9-8fe0-dc1c36dda755.png">

번역본은 다음과 같습니다
<img width="706" alt="Screen Shot 2019-10-18 at 10 12 55 PM" src="https://user-images.githubusercontent.com/25357982/67097225-a12e6f80-f1f4-11e9-935a-791c2e9dab88.png">

이렇게 하나의 문장으로 언급하는 단어들이 있는데 따옴표로 감싸거나, 혹은 글자 그대로 나열하거나 둘중에 하나로 통일해야 할 것 같습니다. 개인적인 소견으로는 번역본 그대로의 형식을 따르는게 더욱 옳지 않을까 싶습니다. 의견 주세요

**Comment by chandryou** [comment]
네 번역본을 그대로 따르는 게 좋겠습니다 ^^

**Comment by SunkyeongLee** [comment]
d599e51683791cf8e2000335a92e34b024dc6b3f
